import { backendApi } from './backendApi'
import { platformApi } from '../platform'

export const services = {
  database: {
    getDatabaseInfo: backendApi.getDatabaseInfo,
    exportDatabase: platformApi.exportDatabase,
    importDatabase: platformApi.importDatabase,
    openDatabaseDirectory: platformApi.openDatabaseDirectory,
  },
  files: {
    openXmindFile: platformApi.openXmindFile,
    parseXmind: platformApi.parseXmind,
    openFilePath: platformApi.openFilePath,
    readFileBuffer: platformApi.readFileBuffer,
    writeExportFiles: platformApi.writeExportFiles,
    writeSingleTextFile: platformApi.writeSingleTextFile,
    writeScreenplayFile: platformApi.writeScreenplayFile,
    openAndReadTextFile: platformApi.openAndReadTextFile,
  },
  exports: {
    exportScreenplayPdf: platformApi.exportScreenplayPdf,
    exportEpub: platformApi.exportEpub,
  },
  books: {
    getBooks: backendApi.getBooks,
    createBook: backendApi.createBook,
    deleteBook: backendApi.deleteBook,
    renameBook: backendApi.renameBook,
    getBookWordCount: backendApi.getBookWordCount,
  },
  screenplay: {
    listScreenplayProjects: backendApi.listScreenplayProjects,
    getScreenplayProject: backendApi.getScreenplayProject,
    getOrCreateScreenplaySession: backendApi.getOrCreateScreenplaySession,
    listScreenplaySessions: backendApi.listScreenplaySessions,
    createScreenplaySession: backendApi.createScreenplaySession,
    createScreenplayProject: backendApi.createScreenplayProject,
    updateScreenplayProject: backendApi.updateScreenplayProject,
    deleteScreenplayProject: backendApi.deleteScreenplayProject,
    listScreenplayDocuments: backendApi.listScreenplayDocuments,
    getScreenplayDocument: backendApi.getScreenplayDocument,
    createScreenplayDocument: backendApi.createScreenplayDocument,
    listScreenplaySourceRefs: backendApi.listScreenplaySourceRefs,
    updateScreenplayDocument: backendApi.updateScreenplayDocument,
    acceptScreenplayDocument: backendApi.acceptScreenplayDocument,
    restoreScreenplayDocument: backendApi.restoreScreenplayDocument,
    deleteScreenplayDocument: backendApi.deleteScreenplayDocument,
  },
  characters: {
    getCharacters: backendApi.getCharacters,
    createCharacter: backendApi.createCharacter,
    updateCharacter: backendApi.updateCharacter,
    deleteCharacter: backendApi.deleteCharacter,
    getCharacterOptions: backendApi.getCharacterOptions,
    addCharacterOption: backendApi.addCharacterOption,
    updateCharacterOption: backendApi.updateCharacterOption,
    deleteCharacterOption: backendApi.deleteCharacterOption,
  },
  settingEntities: {
    getSettingEntities: backendApi.getSettingEntities,
    createSettingEntity: backendApi.createSettingEntity,
    updateSettingEntity: backendApi.updateSettingEntity,
    deleteSettingEntity: backendApi.deleteSettingEntity,
  },
  outlines: {
    saveOutline: backendApi.saveOutline,
    getOutlines: backendApi.getOutlines,
    getVolumeOutlines: backendApi.getVolumeOutlines,
    getOutlineByWritingChapter: backendApi.getOutlineByWritingChapter,
    getOutlineForChapter: backendApi.getOutlineForChapter,
    getGlobalOutline: backendApi.getGlobalOutline,
    ensureGlobalOutline: backendApi.ensureGlobalOutline,
    getWritingOutline: backendApi.getWritingOutline,
    getChapterOutlines: backendApi.getChapterOutlines,
    getAssociableOutlines: backendApi.getAssociableOutlines,
    deleteOutline: backendApi.deleteOutline,
    updateOutline: backendApi.updateOutline,
    listOutlineHistory: backendApi.listOutlineHistory,
    getOutlineHistory: backendApi.getOutlineHistory,
    restoreOutlineHistory: backendApi.restoreOutlineHistory,
  },
  chapters: {
    saveChapters: backendApi.saveChapters,
    getChapters: backendApi.getChapters,
    addChapter: backendApi.addChapter,
    deleteChapter: backendApi.deleteChapter,
    renameChapter: backendApi.renameChapter,
    updateChapterProgress: backendApi.updateChapterProgress,
  },
  articles: {
    saveArticle: backendApi.saveArticle,
    getArticle: backendApi.getArticle,
  },
  storyMemory: {
    analyzeChapterStoryMemory: backendApi.analyzeChapterStoryMemory,
    reviewStoryMemoryDelta: backendApi.reviewStoryMemoryDelta,
    getStoryMemoryEvolutionReview: backendApi.getStoryMemoryEvolutionReview,
    getStoryMemoryVersions: backendApi.getStoryMemoryVersions,
    listStoryMemoryEvolutionReviews: backendApi.listStoryMemoryEvolutionReviews,
    resolveStoryMemoryEvolutionReview: backendApi.resolveStoryMemoryEvolutionReview,
  },
  storyBackground: {
    getStoryBackground: backendApi.getStoryBackground,
    saveStoryBackground: backendApi.saveStoryBackground,
    getStoryBackgroundAttachments: backendApi.getStoryBackgroundAttachments,
    deleteStoryBackgroundAttachment: backendApi.deleteStoryBackgroundAttachment,
    pickStoryBackgroundAttachments: platformApi.pickStoryBackgroundAttachments,
    openStoryBackgroundAttachment: platformApi.openStoryBackgroundAttachment,
  },
  bookStyle: {
    getBookStyle: backendApi.getBookStyle,
    saveBookStyle: backendApi.saveBookStyle,
  },
  history: {
    commitChapterDiff: backendApi.commitChapterDiff,
    listChapterDiff: backendApi.listChapterDiff,
    getChapterDiff: backendApi.getChapterDiff,
    rollbackChapterDiff: backendApi.rollbackChapterDiff,
    commitCharacterSettingDiff: backendApi.commitCharacterSettingDiff,
    commitBackgroundSettingDiff: backendApi.commitBackgroundSettingDiff,
    listCharacterSettingHistory: backendApi.listCharacterSettingHistory,
    getCharacterSettingHistory: backendApi.getCharacterSettingHistory,
    rollbackCharacterSettingHistory: backendApi.rollbackCharacterSettingHistory,
    listBackgroundSettingHistory: backendApi.listBackgroundSettingHistory,
    getBackgroundSettingHistory: backendApi.getBackgroundSettingHistory,
    rollbackBackgroundSettingHistory: backendApi.rollbackBackgroundSettingHistory,
    commitEntitySettingDiff: backendApi.commitEntitySettingDiff,
    listEntitySettingHistory: backendApi.listEntitySettingHistory,
    getEntitySettingHistory: backendApi.getEntitySettingHistory,
    rollbackEntitySettingHistory: backendApi.rollbackEntitySettingHistory,
  },
  sessions: {
    createSession: backendApi.createSession,
    getSessions: backendApi.getSessions,
    setSessionClosed: backendApi.setSessionClosed,
    setSessionReopened: backendApi.setSessionReopened,
    deleteSession: backendApi.deleteSession,
    updateSessionTitle: backendApi.updateSessionTitle,
  },
  conversations: {
    saveConversation: backendApi.saveConversation,
    getConversations: backendApi.getConversations,
    deleteConversationsAfterTurn: backendApi.deleteConversationsAfterTurn,
  },
  favorites: {
    saveAiFavorite: backendApi.saveAiFavorite,
    getAiFavorites: backendApi.getAiFavorites,
    deleteAiFavorite: backendApi.deleteAiFavorite,
  },
  promptTemplates: {
    listPromptTemplates: backendApi.listPromptTemplates,
    createPromptTemplate: backendApi.createPromptTemplate,
    updatePromptTemplate: backendApi.updatePromptTemplate,
    deletePromptTemplate: backendApi.deletePromptTemplate,
    reorderPromptTemplates: backendApi.reorderPromptTemplates,
  },
  memories: {
    addSparkIdea: backendApi.addSparkIdea,
    updateSparkIdea: backendApi.updateSparkIdea,
    deleteSparkIdea: backendApi.deleteSparkIdea,
    getSparkIdeasByBook: backendApi.getSparkIdeasByBook,
    getSparkIdeasByIds: backendApi.getSparkIdeasByIds,
    getSparkIdeasForPrompt: backendApi.getSparkIdeasForPrompt,
    addForeshadowing: backendApi.addForeshadowing,
    updateForeshadowing: backendApi.updateForeshadowing,
    deleteForeshadowing: backendApi.deleteForeshadowing,
    getForeshadowingByBook: backendApi.getForeshadowingByBook,
    getForeshadowingByIds: backendApi.getForeshadowingByIds,
    getForeshadowingForPrompt: backendApi.getForeshadowingForPrompt,
    createMemory: backendApi.createMemory,
    updateMemory: backendApi.updateMemory,
    archiveMemory: backendApi.archiveMemory,
    searchMemories: backendApi.searchMemories,
    listUnifiedMemories: backendApi.listUnifiedMemories,
    getMemoriesByIds: backendApi.getMemoriesByIds,
    linkMemories: backendApi.linkMemories,
    buildMemoryContext: backendApi.buildMemoryContext,
  },
  ai: {
    generateSessionTitle: backendApi.generateSessionTitle,
    listModels: backendApi.listModels,
    getAgentRunSnapshot: backendApi.getAgentRunSnapshot,
    getAgentRunDiagnostics: backendApi.getAgentRunDiagnostics,
    maintainAgentArtifacts: backendApi.maintainAgentArtifacts,
    getAgentRunStabilityTrend: backendApi.getAgentRunStabilityTrend,
    getLatestSessionAgentRun: backendApi.getLatestSessionAgentRun,
    captureAiErrorReport: backendApi.captureAiErrorReport,
    listAiErrorReports: backendApi.listAiErrorReports,
    getAiErrorReport: backendApi.getAiErrorReport,
    submitAiErrorReport: backendApi.submitAiErrorReport,
    cancelAgentRun: backendApi.cancelAgentRun,
    getLongTask: backendApi.getLongTask,
    streamLongTaskConversation: backendApi.streamLongTaskConversation,
    listScreenplayLongTasks: backendApi.listScreenplayLongTasks,
    pauseLongTask: backendApi.pauseLongTask,
    cancelLongTask: backendApi.cancelLongTask,
    createAgentDelegation: backendApi.createAgentDelegation,
    resolveAiToolApproval: backendApi.resolveAiToolApproval,
    aiChatStream: backendApi.aiChatStream,
    abortAiStream: backendApi.abortAiStream,
    onAiChunk: backendApi.onAiChunk,
    debugLog: backendApi.debugLog,
  },
  settings: {
    getSettings: backendApi.getSettings,
    setSettings: backendApi.setSettings,
  },
  dashboard: {
    getStoryHealth: backendApi.getStoryHealth,
    getWritingStats: backendApi.getWritingStats,
    setWritingGoal: backendApi.setWritingGoal,
  },
} as const

export { backendApi }
export { runtimeCapabilities } from '../platform'
