import { backendApi } from './backendApi'
import { platformApi } from '../platform'
import { writingTechniques } from './writingTechniques'

export const services = {
  writingTechniques,
  database: {
    getDatabaseInfo: backendApi.getDatabaseInfo,
    exportDatabase: platformApi.exportDatabase,
    importDatabase: platformApi.importDatabase,
    openDatabaseDirectory: platformApi.openDatabaseDirectory,
  },
  files: {
    openFilePath: platformApi.openFilePath,
    writeExportFiles: platformApi.writeExportFiles,
    writeSingleTextFile: platformApi.writeSingleTextFile,
    writeScreenplayFile: platformApi.writeScreenplayFile,
    openAndReadTextFile: platformApi.openAndReadTextFile,
    pickNovelSourceTextFile: platformApi.pickNovelSourceTextFile,
  },
  exports: {
    exportScreenplayPdf: platformApi.exportScreenplayPdf,
    exportEpub: platformApi.exportEpub,
  },
  books: {
    getBooks: backendApi.getBooks,
    createBook: backendApi.createBook,
    deleteBook: backendApi.deleteBook,
    renameBook: backendApi.renameBook,
    getBookWordCount: backendApi.getBookWordCount,
  },
  screenplay: {
    listScreenplayProjects: backendApi.listScreenplayProjects,
    getOrCreateScreenplaySession: backendApi.getOrCreateScreenplaySession,
    listScreenplaySessions: backendApi.listScreenplaySessions,
    createScreenplaySession: backendApi.createScreenplaySession,
    submitScreenplayConversationTurn:
      backendApi.submitScreenplayConversationTurn,
    getScreenplayConversationSnapshot:
      backendApi.getScreenplayConversationSnapshot,
    watchScreenplayConversationEvents:
      backendApi.watchScreenplayConversationEvents,
    cancelScreenplayConversationTurn:
      backendApi.cancelScreenplayConversationTurn,
    resumeScreenplayConversationOperation:
      backendApi.resumeScreenplayConversationOperation,
    truncateScreenplayConversationFromTurn:
      backendApi.truncateScreenplayConversationFromTurn,
    createScreenplayV2Project: backendApi.createScreenplayV2Project,
    getScreenplayV2Workspace: backendApi.getScreenplayV2Workspace,
    getScreenplayV2Revision: backendApi.getScreenplayV2Revision,
    listScreenplayV2RevisionHistory: backendApi.listScreenplayV2RevisionHistory,
    getScreenplayV2LatestReviewForDraft:
      backendApi.getScreenplayV2LatestReviewForDraft,
    createScreenplayV2WorkingCopyFromRevision:
      backendApi.createScreenplayV2WorkingCopyFromRevision,
    updateScreenplayV2WorkingCopy: backendApi.updateScreenplayV2WorkingCopy,
    publishScreenplayV2WorkingCopy: backendApi.publishScreenplayV2WorkingCopy,
    acceptScreenplayV2Revision: backendApi.acceptScreenplayV2Revision,
    adjudicateScreenplayV2Review: backendApi.adjudicateScreenplayV2Review,
    finalizeScreenplayV2Project: backendApi.finalizeScreenplayV2Project,
    updateScreenplayV2Project: backendApi.updateScreenplayV2Project,
    archiveScreenplayV2Project: backendApi.archiveScreenplayV2Project,
    restoreScreenplayV2Project: backendApi.restoreScreenplayV2Project,
    deleteScreenplayV2Project: backendApi.deleteScreenplayV2Project,
  },
  characters: {
    getCharacters: backendApi.getCharacters,
    createCharacter: backendApi.createCharacter,
    updateCharacter: backendApi.updateCharacter,
    deleteCharacter: backendApi.deleteCharacter,
    getCharacterOptions: backendApi.getCharacterOptions,
    addCharacterOption: backendApi.addCharacterOption,
    updateCharacterOption: backendApi.updateCharacterOption,
    deleteCharacterOption: backendApi.deleteCharacterOption,
  },
  settingEntities: {
    getSettingEntities: backendApi.getSettingEntities,
    createSettingEntity: backendApi.createSettingEntity,
    updateSettingEntity: backendApi.updateSettingEntity,
    deleteSettingEntity: backendApi.deleteSettingEntity,
  },
  outlines: {
    saveOutline: backendApi.saveOutline,
    getVolumeOutlines: backendApi.getVolumeOutlines,
    getOutlineForChapter: backendApi.getOutlineForChapter,
    getGlobalOutline: backendApi.getGlobalOutline,
    ensureGlobalOutline: backendApi.ensureGlobalOutline,
    getWritingOutline: backendApi.getWritingOutline,
    getChapterOutlines: backendApi.getChapterOutlines,
    getAssociableOutlines: backendApi.getAssociableOutlines,
    deleteOutline: backendApi.deleteOutline,
    updateOutline: backendApi.updateOutline,
    listOutlineHistory: backendApi.listOutlineHistory,
    getOutlineHistory: backendApi.getOutlineHistory,
    restoreOutlineHistory: backendApi.restoreOutlineHistory,
  },
  chapters: {
    getChapters: backendApi.getChapters,
    addChapter: backendApi.addChapter,
    deleteChapter: backendApi.deleteChapter,
    renameChapter: backendApi.renameChapter,
  },
  articles: {
    saveArticle: backendApi.saveArticle,
    getArticle: backendApi.getArticle,
  },
  storyMemory: {
    getStoryMemoryVersions: backendApi.getStoryMemoryVersions,
    resolveStoryMemoryEvolutionReview: backendApi.resolveStoryMemoryEvolutionReview,
  },
  storyBackground: {
    getStoryBackground: backendApi.getStoryBackground,
    saveStoryBackground: backendApi.saveStoryBackground,
    getStoryBackgroundAttachments: backendApi.getStoryBackgroundAttachments,
    deleteStoryBackgroundAttachment: backendApi.deleteStoryBackgroundAttachment,
    pickStoryBackgroundAttachments: platformApi.pickStoryBackgroundAttachments,
    openStoryBackgroundAttachment: platformApi.openStoryBackgroundAttachment,
  },
  novelSources: {
    previewImport: backendApi.previewNovelSourceImport,
    confirmImport: backendApi.confirmNovelSourceImport,
    freezeBook: backendApi.freezeBookAsNovelSource,
    list: backendApi.listNovelSources,
    get: backendApi.getNovelSource,
    delete: backendApi.deleteNovelSource,
    getRevision: backendApi.getNovelSourceRevision,
    getSection: backendApi.getNovelSourceSection,
    searchSections: backendApi.searchNovelSourceSections,
    startAnalysis: backendApi.startNovelAnalysis,
    followUpAnalysis: backendApi.followUpNovelAnalysis,
    listAnalysisRuns: backendApi.listNovelAnalysisRuns,
    consumeAnalysisEvents: backendApi.consumeNovelAnalysisEvents,
    pauseAnalysis: backendApi.pauseNovelAnalysis,
    resumeAnalysis: backendApi.resumeNovelAnalysis,
    cancelAnalysis: backendApi.cancelNovelAnalysis,
    getAnalysisArtifact: backendApi.getNovelAnalysisArtifact,
    reviewAnalysisArtifact: backendApi.reviewNovelAnalysisArtifact,
    publishAnalysisArtifact: backendApi.publishNovelAnalysisArtifact,
    listPublishedAnalyses: backendApi.listPublishedNovelAnalyses,
    getPublishedAnalysis: backendApi.getPublishedNovelAnalysis,
  },
  continuations: {
    previewCanon: backendApi.previewContinuationCanon,
    create: backendApi.createContinuation,
    get: backendApi.getContinuation,
    getPlotMaterials: backendApi.getContinuationPlotMaterials,
  },
  history: {
    commitChapterDiff: backendApi.commitChapterDiff,
    listChapterDiff: backendApi.listChapterDiff,
    rollbackChapterDiff: backendApi.rollbackChapterDiff,
    commitCharacterSettingDiff: backendApi.commitCharacterSettingDiff,
    commitBackgroundSettingDiff: backendApi.commitBackgroundSettingDiff,
    listCharacterSettingHistory: backendApi.listCharacterSettingHistory,
    getCharacterSettingHistory: backendApi.getCharacterSettingHistory,
    rollbackCharacterSettingHistory: backendApi.rollbackCharacterSettingHistory,
    listBackgroundSettingHistory: backendApi.listBackgroundSettingHistory,
    getBackgroundSettingHistory: backendApi.getBackgroundSettingHistory,
    rollbackBackgroundSettingHistory: backendApi.rollbackBackgroundSettingHistory,
    commitEntitySettingDiff: backendApi.commitEntitySettingDiff,
    listEntitySettingHistory: backendApi.listEntitySettingHistory,
    getEntitySettingHistory: backendApi.getEntitySettingHistory,
    rollbackEntitySettingHistory: backendApi.rollbackEntitySettingHistory,
  },
  sessions: {
    createSession: backendApi.createSession,
    getSessions: backendApi.getSessions,
    setSessionClosed: backendApi.setSessionClosed,
    setSessionReopened: backendApi.setSessionReopened,
    deleteSession: backendApi.deleteSession,
    updateSessionTitle: backendApi.updateSessionTitle,
  },
  conversations: {
    saveConversation: backendApi.saveConversation,
    getConversations: backendApi.getConversations,
    deleteConversationsAfterTurn: backendApi.deleteConversationsAfterTurn,
  },
  favorites: {
    saveAiFavorite: backendApi.saveAiFavorite,
    getAiFavorites: backendApi.getAiFavorites,
    deleteAiFavorite: backendApi.deleteAiFavorite,
  },
  promptTemplates: {
    listPromptTemplates: backendApi.listPromptTemplates,
    createPromptTemplate: backendApi.createPromptTemplate,
    updatePromptTemplate: backendApi.updatePromptTemplate,
    deletePromptTemplate: backendApi.deletePromptTemplate,
  },
  memories: {
    addSparkIdea: backendApi.addSparkIdea,
    updateSparkIdea: backendApi.updateSparkIdea,
    deleteSparkIdea: backendApi.deleteSparkIdea,
    getSparkIdeasByBook: backendApi.getSparkIdeasByBook,
    addForeshadowing: backendApi.addForeshadowing,
    updateForeshadowing: backendApi.updateForeshadowing,
    deleteForeshadowing: backendApi.deleteForeshadowing,
    getForeshadowingByBook: backendApi.getForeshadowingByBook,
    createMemory: backendApi.createMemory,
    updateMemory: backendApi.updateMemory,
    setMemoryState: backendApi.setMemoryState,
    listUnifiedMemories: backendApi.listUnifiedMemories,
    linkMemories: backendApi.linkMemories,
    reviewMemory: backendApi.reviewMemory,
    resolveMemories: backendApi.resolveMemories,
    deleteMemory: backendApi.deleteMemory,
    getMemoryHistory: backendApi.getMemoryHistory,
    getMemoryLinks: backendApi.getMemoryLinks,
    buildMemoryContext: backendApi.buildMemoryContext,
  },
  ai: {
    generateSessionTitle: backendApi.generateSessionTitle,
    getAgentRunSnapshot: backendApi.getAgentRunSnapshot,
    getSubAgentConversation: backendApi.getSubAgentConversation,
    consumeAgentRunEvents: backendApi.consumeAgentRunEvents,
    getAgentRunPlannerDiagnostics: backendApi.getAgentRunPlannerDiagnostics,
    getAgentRunModelInputDiagnostics: backendApi.getAgentRunModelInputDiagnostics,
    getAgentRunToolDiagnostics: backendApi.getAgentRunToolDiagnostics,
    getLatestSessionAgentRun: backendApi.getLatestSessionAgentRun,
    submitAiErrorReport: backendApi.submitAiErrorReport,
    cancelAgentRun: backendApi.cancelAgentRun,
    cancelWritingChatRequest: backendApi.cancelWritingChatRequest,
    resolveAiToolApproval: backendApi.resolveAiToolApproval,
    aiChatStream: backendApi.aiChatStream,
    abortAiStream: backendApi.abortAiStream,
    onAiChunk: backendApi.onAiChunk,
  },
  settings: {
    getSettings: backendApi.getSettings,
    setSettings: backendApi.setSettings,
  },
  dashboard: {
    getStoryHealth: backendApi.getStoryHealth,
    getWritingStats: backendApi.getWritingStats,
    setWritingGoal: backendApi.setWritingGoal,
  },
} as const

export { backendApi }
export { runtimeCapabilities } from '../platform'
