"""Frozen transport rules for pre-descriptor persisted requests. Do not regenerate from the current catalog."""

LEGACY_CODECS = {'zai:glm-5.3-flash': {'schemaVersion': 1,
                       'profileId': 'zai:glm-5.3-flash',
                       'reasoningControl': 'always_enabled',
                       'outputTokenParameter': 'max_tokens',
                       'nativeAnthropicThinking': False,
                       'openaiExtraBodies': {'default': {'thinking': {'type': 'enabled'}},
                                             'enabled': {'thinking': {'type': 'enabled'}},
                                             'disabled': None},
                       'streamUsage': True},
 'deepseek:deepseek-v4-flash': {'schemaVersion': 1,
                                'profileId': 'deepseek:deepseek-v4-flash',
                                'reasoningControl': 'selectable',
                                'outputTokenParameter': 'max_tokens',
                                'nativeAnthropicThinking': False,
                                'openaiExtraBodies': {'default': {},
                                                      'enabled': {'thinking': {'type': 'enabled'}},
                                                      'disabled': {'thinking': {'type': 'disabled'}}},
                                'streamUsage': True},
 'moonshot:kimi-k3': {'schemaVersion': 1,
                      'profileId': 'moonshot:kimi-k3',
                      'reasoningControl': 'always_enabled',
                      'outputTokenParameter': 'max_completion_tokens',
                      'nativeAnthropicThinking': False,
                      'openaiExtraBodies': {'default': {'reasoning_effort': 'max'},
                                            'enabled': {'reasoning_effort': 'max'},
                                            'disabled': None},
                      'streamUsage': True},
 'moonshot:kimi-k2.6': {'schemaVersion': 1,
                        'profileId': 'moonshot:kimi-k2.6',
                        'reasoningControl': 'selectable',
                        'outputTokenParameter': 'max_completion_tokens',
                        'nativeAnthropicThinking': False,
                        'openaiExtraBodies': {'default': {},
                                              'enabled': {'thinking': {'type': 'enabled'}},
                                              'disabled': {'thinking': {'type': 'disabled'}}},
                        'streamUsage': True},
 'minimax:MiniMax-M3': {'schemaVersion': 1,
                        'profileId': 'minimax:MiniMax-M3',
                        'reasoningControl': 'selectable',
                        'outputTokenParameter': 'max_completion_tokens',
                        'nativeAnthropicThinking': True,
                        'openaiExtraBodies': {'default': {'reasoning_split': True},
                                              'enabled': {'reasoning_split': True,
                                                          'thinking': {'type': 'adaptive'}},
                                              'disabled': {'reasoning_split': True,
                                                           'thinking': {'type': 'disabled'}}},
                        'streamUsage': True},
 'mimo:mimo-v2.5-pro': {'schemaVersion': 1,
                        'profileId': 'mimo:mimo-v2.5-pro',
                        'reasoningControl': 'selectable',
                        'outputTokenParameter': 'max_tokens',
                        'nativeAnthropicThinking': False,
                        'openaiExtraBodies': {'default': {},
                                              'enabled': {'thinking': {'type': 'enabled'}},
                                              'disabled': {'thinking': {'type': 'disabled'}}},
                        'streamUsage': True}}
