"""Generate the renderer's offline capability snapshot from backend profiles."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from infrastructure.models.profiles.descriptors import model_descriptors


def generated_source():
    return "// Generated by scripts/generate-model-descriptors.py; do not edit.\nexport const MODEL_DESCRIPTORS = " + json.dumps(model_descriptors(), ensure_ascii=False, indent=2) + " as const\n"


if __name__ == "__main__":
    target = ROOT / "src/models/descriptors.generated.ts"
    source = generated_source()
    if "--check" in sys.argv:
        if not target.is_file() or target.read_text() != source:
            raise SystemExit("Model descriptors are stale; run .venv/bin/python scripts/generate-model-descriptors.py")
    else:
        target.write_text(source)
