// Generated by scripts/generate-model-descriptors.py; do not edit.
export const MODEL_DESCRIPTORS = [
  {
    "schemaVersion": 1,
    "profileId": "zai:glm-5.3-flash",
    "modelNames": [
      "glm-5.3-flash"
    ],
    "baseUrls": [
      "https://open.bigmodel.cn/api/paas/v4"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": true,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 131072,
    "reasoningControl": "always_enabled",
    "reasoningEffortOptions": [
      "low",
      "high",
      "max"
    ],
    "taskReasoningPreferences": {
      "economical": "low"
    },
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {
        "thinking": {
          "type": "enabled"
        }
      },
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": null
    },
    "streamUsage": true,
    "source": "https://docs.z.ai/guides/vlm/glm-5.3-flash",
    "digest": "6c7ebd90b0f04a3b4f34a3baf1dbf662f47c3e8fffe2c4bfb703db0f78bf8dc6"
  },
  {
    "schemaVersion": 1,
    "profileId": "deepseek:deepseek-v4-flash",
    "modelNames": [
      "deepseek-v4-flash"
    ],
    "baseUrls": [
      "https://api.deepseek.com",
      "https://api.deepseek.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 393216,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [
      "low",
      "high",
      "max"
    ],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://api-docs.deepseek.com/quick_start/pricing",
    "digest": "49dfe3130288b41159029da62b53399ff8e77bcdc0694d38ea3b5dae3d615b63"
  },
  {
    "schemaVersion": 1,
    "profileId": "moonshot:kimi-k3",
    "modelNames": [
      "kimi-k3"
    ],
    "baseUrls": [
      "https://api.moonshot.ai/v1",
      "https://api.moonshot.cn/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 1048576,
    "reasoningControl": "always_enabled",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_completion_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {
        "reasoning_effort": "max"
      },
      "enabled": {
        "reasoning_effort": "max"
      },
      "disabled": null
    },
    "streamUsage": true,
    "source": "https://platform.kimi.ai/docs/guide/kimi-k3-quickstart",
    "digest": "272992c156ad44ae3ff6e7cd413ae34a70d840480425dd9618544b9f5e5d36b5"
  },
  {
    "schemaVersion": 1,
    "profileId": "moonshot:kimi-k2.6",
    "modelNames": [
      "kimi-k2.6"
    ],
    "baseUrls": [
      "https://api.moonshot.ai/v1",
      "https://api.moonshot.cn/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "128k",
      "256k"
    ],
    "defaultContextWindow": "256k",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 0.6,
    "maxGenerationTokens": 262144,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_completion_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://platform.kimi.ai/docs/guide/kimi-k2-6-quickstart",
    "digest": "930fbfbef2d093d3ec2dff87d906fb3d69d23b0a564ca1597f322980e9806040"
  },
  {
    "schemaVersion": 1,
    "profileId": "minimax:MiniMax-M3",
    "modelNames": [
      "minimax-m3",
      "minimax-m3.0"
    ],
    "baseUrls": [
      "https://api.minimax.io/anthropic",
      "https://api.minimax.io/v1",
      "https://api.minimaxi.com/anthropic",
      "https://api.minimaxi.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 524288,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_completion_tokens",
    "nativeAnthropicThinking": true,
    "openaiExtraBodies": {
      "default": {
        "reasoning_split": true
      },
      "enabled": {
        "reasoning_split": true,
        "thinking": {
          "type": "adaptive"
        }
      },
      "disabled": {
        "reasoning_split": true,
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://platform.minimaxi.com/docs/api-reference/text-chat-openai",
    "digest": "1444b611b4776236b5db8dcf9c0c43d0622b599efdb86f566e7f4e7777ae0fdf"
  },
  {
    "schemaVersion": 1,
    "profileId": "mimo:mimo-v2.5-pro",
    "modelNames": [
      "mimo-v2.5-pro"
    ],
    "baseUrls": [
      "https://api.xiaomimimo.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": false,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 0.6,
    "defaultTemperatureNonThinking": 0.6,
    "maxGenerationTokens": 131072,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://mimo.mi.com/docs/en-US/api/chat/responses",
    "digest": "c43310c80bed7c5607c651583397a05aa5de6697b1954212886a02298ed1dbae"
  }
] as const
