// Generated by scripts/generate-model-descriptors.py; do not edit.
export const MODEL_DESCRIPTORS = [
  {
    "schemaVersion": 1,
    "profileId": "zai",
    "modelNames": [],
    "baseUrls": [
      "https://open.bigmodel.cn/api/paas/v4"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": true,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 131072,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [
      "low",
      "high",
      "max"
    ],
    "taskReasoningPreferences": {
      "economical": "low"
    },
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://docs.z.ai/guides/vlm/glm-5.3-flash",
    "digest": "a51b8cb83de645bdb098e58921617841d31ecc94f0ba40b17c7e728236320271"
  },
  {
    "schemaVersion": 1,
    "profileId": "deepseek",
    "modelNames": [],
    "baseUrls": [
      "https://api.deepseek.com",
      "https://api.deepseek.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 393216,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [
      "low",
      "high",
      "max"
    ],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://api-docs.deepseek.com/quick_start/pricing",
    "digest": "4055c315161f14d1ff33ef0d292bab005e54df3d865bb15e70ddf20e3f6a36b0"
  },
  {
    "schemaVersion": 1,
    "profileId": "moonshot",
    "modelNames": [],
    "baseUrls": [
      "https://api.moonshot.ai/v1",
      "https://api.moonshot.cn/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "128k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "256k",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 0.6,
    "maxGenerationTokens": 1048576,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_completion_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://platform.kimi.ai/docs/guide/kimi-k3-quickstart",
    "digest": "9ae76d5a010651259a0b9b747f263767ec38eb32b162be83b82845b9ce16bb01"
  },
  {
    "schemaVersion": 1,
    "profileId": "minimax",
    "modelNames": [],
    "baseUrls": [
      "https://api.minimax.io/anthropic",
      "https://api.minimax.io/v1",
      "https://api.minimaxi.com/anthropic",
      "https://api.minimaxi.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": true,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 1,
    "defaultTemperatureNonThinking": 1,
    "maxGenerationTokens": 524288,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_completion_tokens",
    "nativeAnthropicThinking": true,
    "openaiExtraBodies": {
      "default": {
        "reasoning_split": true
      },
      "enabled": {
        "reasoning_split": true,
        "thinking": {
          "type": "adaptive"
        }
      },
      "disabled": {
        "reasoning_split": true,
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://platform.minimaxi.com/docs/api-reference/text-chat-openai",
    "digest": "51e6ef82913ba90ce66b8c5d754cbf7bef9e9400710fddd7da14067d6a20388f"
  },
  {
    "schemaVersion": 1,
    "profileId": "mimo",
    "modelNames": [],
    "baseUrls": [
      "https://api.xiaomimimo.com/v1"
    ],
    "contextWindowOptions": [
      "32k",
      "256k",
      "1m"
    ],
    "defaultContextWindow": "1m",
    "defaultThinkingEnabled": false,
    "customizeTemperature": false,
    "defaultTemperatureThinking": 0.6,
    "defaultTemperatureNonThinking": 0.6,
    "maxGenerationTokens": 131072,
    "reasoningControl": "selectable",
    "reasoningEffortOptions": [],
    "taskReasoningPreferences": {},
    "outputTokenParameter": "max_tokens",
    "nativeAnthropicThinking": false,
    "openaiExtraBodies": {
      "default": {},
      "enabled": {
        "thinking": {
          "type": "enabled"
        }
      },
      "disabled": {
        "thinking": {
          "type": "disabled"
        }
      }
    },
    "streamUsage": true,
    "source": "https://mimo.mi.com/docs/en-US/api/chat/responses",
    "digest": "07eb86cc775479893d7d6327070ac4cef58c41f363e307033e5a99318531de3b"
  }
] as const
